#!/bin/bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:10:00

set -e
set -x

singularity exec docker://brainlifemeeg/mne:1.12.1 python3 main.py

cat << EOF > product.json
{
    "brainlife": [
       {
         "type": "image/png",
	       "name": "Joint plot",
         "base64": "$(base64 -w 0 out_figs/joint-plot.png)"
       }
]
}
EOF
